// Acceptance for user-facing summaries and measured/proposed Schema goals.
// Run against the lifecycle project after the reviewed schema-goal MCP package.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const [base, project, output] = process.argv.slice(2);
  if (!base || !project || !output || fs.existsSync(output)) throw new Error('base, project and unused evidence directory required');
  fs.mkdirSync(output, {recursive:true});
  const browser = await chromium.launch({headless:true, executablePath:process.env.PLAYWRIGHT_CHROMIUM_PATH || undefined});
  const page = await browser.newPage({viewport:{width:1720,height:1100}});
  const checks=[],errors=[],writes=[];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => {if(r.method() !== 'GET' && !(r.method()==='POST' && new URL(r.url()).pathname==='/api/search')) writes.push(r.url());});
  const visible = async selector => page.waitForFunction(s => {const r=document.querySelector(s)?.getBoundingClientRect();return r && r.top>=70 && r.top<330;}, selector);
  try {
    const snapshot=await (await page.request.get(`${base}/api/snapshot?project_id=${encodeURIComponent(project)}`)).json();
    const schemas=snapshot.nodes.filter(n=>n.entity_kind==='schema');
    assert.equal(schemas.length,6);
    await page.goto(`${base}/?project=${encodeURIComponent(project)}`,{waitUntil:'networkidle'});
    assert.equal(await page.locator('.project-schema-row').count(),6);
    await page.waitForFunction(id=>document.querySelector('#record-meta').textContent.includes(id),snapshot.root_revision_id);
    assert.equal(await page.locator('#goal-state .schema-goal').count(),1);
    assert.equal(await page.locator('.project-schema-row .schema-progress-percent').count(),6);
    assert.equal(await page.locator('#project-goal-progress .goal-progress-percent').count(),1);
    assert.match(await page.locator('#project-schema-summary').innerText(),/AI 0\/3 · 미측정 3/);
    assert.match(await page.locator('#project-goal-progress').innerText(),/AI 예상 달성률 약/);
    checks.push('six Schema goal summaries and independently estimated Project goal are visible');
    const displayed=await page.locator('body').innerText();
    assert.ok(!displayed.includes(project.replace(/_project$/,'')), 'application IDs leaked into default visible summary');
    assert.ok(!/sha256:[a-f0-9]|(?:rev|hc)_[a-f0-9]{12}/.test(displayed), 'technical hashes leaked into default visible summary');
    assert.ok(!(await page.locator('.technical-details').first().getAttribute('open')));
    await page.locator('.technical-details summary').first().click();
    assert.ok((await page.locator('#record-meta').innerText()).includes(snapshot.root_revision_id));
    await page.locator('.technical-details summary').first().click();
    checks.push('IDs and hashes hidden by default while technical details remain inspectable');
    assert.ok(await page.locator('#version-diff ins').count()>0);
    assert.ok(await page.locator('#version-diff del').count()>0);
    assert.match(await page.locator('#version-diff').innerText(),/변경된 역할 또는 연결/);
    checks.push('current project revision shows highlighted before/after text and composition changes');
    await page.screenshot({path:path.join(output,'summary-desktop.png')});
    await page.locator('#view-3d').click();
    await visible('#graph-title');
    const first=schemas.find(node=>node.revision_id===snapshot.tree.children[0].revision_id),second=schemas.find(node=>node.revision_id===snapshot.tree.children[1].revision_id);
    await page.locator(`#tree .tree-item[data-record-id="${first.revision_id}"]`).click();
    await page.waitForFunction(id=>document.querySelector('#record-meta').textContent.includes(id),first.revision_id);
    await visible('#record-title');
    assert.equal(await page.locator('#goal-state .schema-goal').count(),1);
    assert.equal(await page.locator('#goal-state .goal-numeric li').count(),3);
    const candidates=page.locator('#version-diff .diff-candidates button');
    if(await candidates.count()) await candidates.first().click();
    assert.ok(await page.locator('#version-diff .diff-copy').isVisible());
    checks.push('left Schema selection in 3D reveals changed detail and its three goal criteria immediately; real predecessor comparison works');
    await page.screenshot({path:path.join(output,'selected-schema-diff.png')});
    await page.locator(`#tree .tree-item[data-record-id="${second.revision_id}"]`).click();
    await page.waitForFunction(id=>document.querySelector('#record-meta').textContent.includes(id),second.revision_id);
    await visible('#record-title');
    assert.ok((await page.locator('#current-selection').innerText()).includes(second.title));
    checks.push('second navigation click updates visible selection, content, diff and Schema scope');
    await page.locator('#view-2d').click();
    await page.locator('#timeline .timeline-button').filter({hasText:'escaped_card_count'}).first().click();
    await page.waitForFunction(()=>document.querySelector('#tree-summary').textContent.includes('선택한 이력'));
    const exported=await(await page.request.get(`${base}/api/export?project_id=${project}&include_receipts=false`)).json();
    const observation=exported.content.records.find(r=>r.kind==='observation'&&r.data.metric==='escaped_card_count');
    await page.locator(`#tree .tree-item[data-record-id="${observation.data.target_revision_id}"]`).click();
    await page.waitForFunction(()=>document.querySelector('#goal-state').textContent.includes('실제 측정 3'));
    assert.match(await page.locator('#goal-state').innerText(),/목표 기준 ≥ 2 cards/);
    assert.equal(await page.locator('#goal-state .goal-numeric li').count(),1);
    assert.ok(!(await page.locator('#goal-state').innerText()).includes('AI 추정값'));
    await page.screenshot({path:path.join(output,'historical-measured-goal.png')});
    await page.locator('#latest-button').click();
    await page.waitForFunction(()=>document.querySelector('#project-goal-progress').textContent.includes('AI 예상 달성률 약 20%'));
    await page.waitForFunction(id=>document.querySelector('#record-meta').textContent.includes(id) && !document.querySelector('#record-detail').hidden,snapshot.root_revision_id);
    checks.push('historical v2 measured 3 against target 2 is visible; latest returns to independent v3 Project and Schema estimates without inheriting past completion');
    await page.setViewportSize({width:1280,height:900});
    await page.evaluate(()=>{window.scrollTo(0,0);document.querySelector('.record-pane').scrollTop=0;document.querySelector('.insights').scrollTop=0;});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
    await page.screenshot({path:path.join(output,'summary-laptop.png')});
    checks.push('desktop and laptop summaries remain readable without horizontal overflow');
    assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
    checks.push('no JavaScript errors or dashboard writes');
    fs.writeFileSync(path.join(output,'report.json'),JSON.stringify({status:'passed',checks,errors,writes},null,2));
  } catch(error) {
    await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});
    fs.writeFileSync(path.join(output,'report.json'),JSON.stringify({status:'failed',error:String(error),checks,errors,writes},null,2));
    throw error;
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
